version: "3.7"
services:
  flake8:
    image: wonkyto/bom-influxdb-loader:1.0.0
    command: flake8
    volumes:
      - ./app:/app
    working_dir: /app
  run:
    image: wonkyto/bom-influxdb-loader:1.0.0
    volumes:
      - ./config:/config
    working_dir: /app
  test:
    image: wonkyto/bom-influxdb-loader:1.0.0
    volumes:
      - ./app:/app
      - ./config:/config
    working_dir: /app
