services:
  lint:
    build:
      context: .
      target: dev
    command: ruff check /app
    volumes:
      - ./app:/app

  format:
    build:
      context: .
      target: dev
    command: ruff format --check /app
    volumes:
      - ./app:/app

  pytest:
    build:
      context: .
      target: dev
    command: pytest /tests
    volumes:
      - ./app:/app
      - ./config:/config
      - ./tests:/tests

  run:
    image: wonkyto/bom-influxdb-loader:1.1.0
    volumes:
      - ./config:/config
    working_dir: /app

  test:
    image: wonkyto/bom-influxdb-loader:1.1.0
    volumes:
      - ./app:/app
      - ./config:/config
    working_dir: /app
